In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("D:/Code/python/mat3533/practice05/data/iris.data")
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [8]:
df['Iris-setosa'] = df['Iris-setosa'].map({'Iris-setosa' : 0,'Iris-versicolor' : 1, 'Iris-virginica': 2})
df

     5.1  3.5  1.4  0.2  Iris-setosa
0    4.9  3.0  1.4  0.2            0
1    4.7  3.2  1.3  0.2            0
2    4.6  3.1  1.5  0.2            0
3    5.0  3.6  1.4  0.2            0
4    5.4  3.9  1.7  0.4            0
..   ...  ...  ...  ...          ...
144  6.7  3.0  5.2  2.3            2
145  6.3  2.5  5.0  1.9            2
146  6.5  3.0  5.2  2.0            2
147  6.2  3.4  5.4  2.3            2
148  5.9  3.0  5.1  1.8            2

[149 rows x 5 columns]

In [30]:
y = df.iloc[:, 4].values.tolist()
X = df.iloc[:, 0:4]
y = np.array(y)
X = np.array(X).T

In [25]:
def softmax(V):
    e_V = np.exp(V - np.max(V, axis = 0, keepdims = True))
    Z = e_V / e_V.sum(axis = 0)
    return Z

In [26]:
def cost(Y, Yhat):
    return -np.sum(Y*np.log(Yhat))/Y.shape[1]

In [27]:
## One-hot coding
from scipy import sparse
def convert_labels(y, C = 3):
    Y = sparse.coo_matrix((np.ones_like(y),
    (y, np.arange(len(y)))), shape = (C, len(y))).toarray()
    return Y

In [31]:
d0 = X.shape[0]

d1 = h = 100 # size of hidden layer

d2 = C = 3
# initialize parameters randomly
W1 = 0.01*np.random.randn(d0, d1)
b1 = np.zeros((d1, 1))
W2 = 0.01*np.random.randn(d1, d2)
b2 = np.zeros((d2, 1))

Y = convert_labels(y, C)
N = X.shape[1]
eta = 1 # learning rate

In [32]:
for i in range(10000):
    ## Feedforward
    Z1 = np.dot(W1.T, X) + b1
    A1 = np.maximum(Z1, 0)
    Z2 = np.dot(W2.T, A1) + b2
    Yhat = softmax(Z2)

    # print loss after each 1000 iterations
    if i %1000 == 0:
        # compute the loss: average cross-entropy loss
        loss = cost(Y, Yhat)
        print("iter %d, loss: %f" %(i, loss))

    # backpropagation
    E2 = (Yhat - Y )/N
    dW2 = np.dot(A1, E2.T)
    db2 = np.sum(E2, axis = 1, keepdims = True)
    E1 = np.dot(W2, E2)
    E1[Z1 <= 0] = 0 # gradient of ReLU
    dW1 = np.dot(X, E1.T)
    db1 = np.sum(E1, axis = 1, keepdims = True)
    # Gradient Descent update
    W1 += -eta*dW1
    b1 += -eta*db1
    W2 += -eta*dW2
    b2 += -eta*db2

iter 0, loss: 1.098175
iter 1000, loss: 1.098567
iter 2000, loss: 1.098567
iter 3000, loss: 1.098567
iter 4000, loss: 1.098567
iter 5000, loss: 1.098567
iter 6000, loss: 1.098567
iter 7000, loss: 1.098567
iter 8000, loss: 1.098567
iter 9000, loss: 1.098567

In [33]:
Z1 = np.dot(W1.T, X) + b1
A1 = np.maximum(Z1, 0)
Z2 = np.dot(W2.T, A1) + b2
predicted_class = np.argmax(Z2, axis=0)
acc = 100*np.mean(predicted_class == y)
print('training accuracy: %.2f %%' % (acc))

training accuracy: 33.56 %